spring:
  application:
    name: ms1-user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ms1-user-service?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: passer
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
